{% set name = "text-encrypt-decrypt" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b01a20172746918c1cf01edae57356697aa7840f784d21a41ad81183ba5c28ef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cryptography
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - text_encrypt_decrypt

about:
  home: https://github.com/sujitmandal/text-encrypt-decrypt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: plain text encrypt decrypt, plain text encryption and decryption with SHA256 algorithm.
  doc_url: https://github.com/sujitmandal/text-encrypt-decrypt/
  dev_url: https://github.com/sujitmandal/text-encrypt-decrypt/

extra:
  recipe-maintainers:
    - sujitmandal
